### ISSUE TITLE
Round up or down in stats

### ISSUE THREAD

**Issue by HerDataSam** [MalitsPlus/ShizuruNotes#16]
I realized that some of the stats have differences between calculated value and in-game value. It seemed that you have applied RoundingMode.DOWN in buildExpression function in the ActionParameter.java, but I think RoundingMode.HALF_UP is correct for Chara skill value. Is there any reason for RoundingMode.DOWN? Is it wrong for Boss skills? I want to know whether it has a side-effect.

----
Edit) One more thing. I think it is better to apply a ceiling function on UniqueEquipmentProperty after adding multiplied enhancement data. To be sure, in イオ's unique equipment, a base stat of energy recovery rate(TP) is 1 and its enhance rate is 0.05. Its in-game value in Lv.2 is ceil(1+0.05 * 1) = 2. So, the calculated data need to be _ceil_ ed before adding to Chara stats. Sorry for Korean language, but I hope you could understand it with numbers :)

![イオunique](https://user-images.githubusercontent.com/64837046/82180523-a8009a80-991b-11ea-8f0b-cb3878478f6f.png)

**Comment by MalitsPlus** [comment]
Ummm yes, I check this from source code, and it shows that you are right. 
Thank you for reminding me to notice this, I will fix it in the future release. 

![basepara](https://user-images.githubusercontent.com/50281195/82182811-72f24900-9917-11ea-818d-d3bde0fe302d.png)
![uniqueequip](https://user-images.githubusercontent.com/50281195/82182815-74bc0c80-9917-11ea-80af-50f7b24bb277.png)

**Comment by MalitsPlus** [comment]
Oh, you mean `buildExpression()` in `ActionParameter`. The rounding mode of it is different depending on the `ActionType`. 
If you mean `DamageAction`, I'm sure the rounding mode of it is `RoundingMode.DOWN` according to source code. 

(`num4` is the damage point int the picture)
![image](https://user-images.githubusercontent.com/50281195/82195495-f36e7500-992a-11ea-9ca3-883360a660c3.png)

**Comment by HerDataSam** [comment]
Oh, so it should be determined by its `ActionType`. Then, I'll change the code of `ChangeEnergyAction`, while leaving the `buildExpression()` code as it is. I checked that issue in ジータ's 2nd skill. In Korean server, where her level is 127, it should be `RoundingMode.HALF_UP` to be `341` as the in-game value when the equation is `150 + 1.5 * level`. To be correct, I should change the `roundingMode` parameter from `null` to `RoundingMode.HALF_UP` in the `ChangeEnergyAction`. And I should check if there are anything more to change.

By the way, how did you get the original source code? Is it confidential but you leaked? I don't need all of the codes, but I just want to look into some more codes. 

![ジータ2nd](https://user-images.githubusercontent.com/64837046/82198957-00de2c00-9938-11ea-9755-15ee5fe6dde8.jpg)

**Comment by MalitsPlus** [comment]
I've send you an invitation, please check your email. 
And then I will hide this thread.
