### ISSUE TITLE
公会战历史boss数据不全

### ISSUE THREAD

**Issue by kourindoupota** [MalitsPlus/ShizuruNotes#18]
翻了下发现只有到19年5月的数据？请问是我的问题还是只有这些？谢谢

**Comment by MalitsPlus** [comment]
[源码](https://github.com/MalitsPlus/ShizuruNotes/blob/2bfac3b56136c3da71a41b1f656d496af6b8e438/app/src/main/java/com/github/malitsplus/shizurunotes/db/DBHelper.kt#L732)里写的有，1014以前的结构和现在的不同，本身又是过气数据我就懒得解析直接排除了

**Comment by kourindoupota** [comment]
明白了，谢谢大佬解答
