### ISSUE TITLE
关于最新版本技能数值公式

### ISSUE THREAD

**Issue by he2yutong** [MalitsPlus/ShizuruNotes#20]
在设定里，开启显示公式，原本技能数值就会消失，我不知道是不是bug。如果可以公式和技能最终计算数值一起显示的话，会很方便一些数据的比较，非常感谢。

**Comment by MalitsPlus** [comment]
数值和公式只能显示其中之一。
至于两者塞一起，个人不太喜欢这种杂乱的展示方式。不过有时间我可以做一个快捷切换展示方式的按钮。

**Comment by he2yutong** [comment]
感谢回复。如果您觉得影响美观的话，那的确是不好解决了，我也尊重您的选择。
        但就我这样喜欢研究jjc的玩家来说，技能的数值和影响技能数值的因素是同等重要的，如果能同时显示会很方便一些阵容的思路搭配。
        比如静流，如果光看公式，对于她的ub伤害我不能很好地把握，在看了技能数值后，她在前卫中高达1.2w左右的ub物理伤害，能更好地方便我给她定位，我也时常用她的ub来处理残局后排，效果很不错。
        而数值公式显示，4.8的高额物理加成（同比下，一般物理角只有3.6）又能让我决定给她升星，因为她的高额加成决定了5星ex+物理加成能有高收益，她的奶人技能也能得到很好的加强。
        如果这两个条件缺一个的话，对一个角色而言，她的定位、强度、升星与否都会变得不确定起来，这对于在意细节的jjc玩家来说，是很不方便的，所以还请多思量一下。
        感谢看完。

**Comment by he2yutong** [comment]
感谢回复，我很赞同您的决定。数值和公式同时显示或切换的功能，对于jjc玩家角色定位和规划来说非常重要。比如静流，她的ub伤害在前卫中高达1.2w，并且有着4.8的高额加成。前者让我对静流伤害有个大致把握，我因此常用静流处理后排残局，效果不错。而后者的高额加成，让我决定给静流升5星，因为ex+的物理攻击力能有效的提高ub和奶量。所以期待功能的尽快正式上线。
感谢您耐心看完。

**Comment by MalitsPlus** [comment]
ver1.0.0已追加
