### ISSUE TITLE
部分装备与掉落欠缺

### ISSUE THREAD

**Issue by redappletea** [MalitsPlus/ShizuruNotes#26]
数据库版本：10020800
app版本：1.0.3

1.找不到的聖円環ヘブンリーロータス的掉落信息。

望核实修复

**Comment by MalitsPlus** [comment]
![Screenshot_20200829-021932](https://user-images.githubusercontent.com/50281195/91595371-6497dc80-e99e-11ea-82aa-3168a96d2ed4.jpg)
![Screenshot_20200829-021849](https://user-images.githubusercontent.com/50281195/91595384-695c9080-e99e-11ea-843d-7a7716a86e7e.jpg)

有的，在比较后面的地方。
