### ISSUE TITLE
国服环奈数据更新

### ISSUE THREAD

**Issue by kokoronoinori** [MalitsPlus/ShizuruNotes#31]
在nga看到app有环奈数据 但个人app上升级了数次数据库均没有更新 想问一下如何获得数据

app版本 1.06
数据库版本 10022280
语音简体中文

![Screenshot_2020-10-19-15-30-03-580_com github malitsplus shizurunotes](https://user-images.githubusercontent.com/22474937/96414630-f940ed00-121f-11eb-87a1-9b4d1b2baf47.jpg)

**Comment by MalitsPlus** [comment]
目前静流笔记暂未支持国服数据，你看到的可能是有人自己针对国服数据对app进行修改编译的版本。
