### ISSUE TITLE
A rounding rule in AilmentAction

### ISSUE THREAD

**Issue by HerDataSam** [MalitsPlus/ShizuruNotes#33]
1. A rounding rule of dot damages

SLIP_DAMAGE which comes from ailments should be rounded down. It is because the result value ends with the conversion `(long)`, and this conversion drops the floating-point numbers in the CSharp. This issue is suggested by a Korean user who compared the values between in-game damage of Mitsuki's 'Curse Bloom+' and Aoi's 'Poison Arrow+', and Notes' calculated damage.

https://github.com/MalitsPlus/ShizuruNotes/blob/a9e319fc727f2a5433f764531fb74d60b0c377d5/app/src/main/java/com/github/malitsplus/shizurunotes/data/action/AilmentAction.java#L70-L81

If there are any client updates about this calculation, you can ignore it. 

2. A potential error

`%s` is missed at the second line of the code below, while zh version is fine.

https://github.com/MalitsPlus/ShizuruNotes/blob/ce0c518f0ed4fa32ca5ee66da5c06a924b2bb1f1/app/src/main/res/values/strings.xml#L674-L675

Thanks.

**Comment by MalitsPlus** [comment]
I've checked about this, the entire conversion is double→float→int→long, thus it seems that you are right, I'll fix it later. Thx a lot!
