### ISSUE TITLE
关于直接读取本机PCR数据库的一点想法

### ISSUE THREAD

**Issue by lmhstcscr** [MalitsPlus/ShizuruNotes#34]
今天翻PCR数据的时候发现原来数据库文件本体就存在数据文件目录下
data\com.bilibili.priconne\files\manifest.mdb （国服）
两者不论大小和内容我连接了一下看都是一样的，应该就是文件本体。
是否可以考虑做一个连本机PCR的接口，这样游戏维护完更新了，自己就可以同步到静流笔记上，也（一定程度）可以减缓estertion大佬那边的流量压力和更新前后的短时服务器压力？

**Comment by HerDataSam** [comment]
Is it accessible without the root permission?

**Comment by lmhstcscr** [comment]
> Is it accessible without the root permission?

Oh i forgot this...  Root permission is required... so it may be difficult to achieve...

**Comment by MalitsPlus** [comment]
参考 [官方文档](https://developer.android.google.cn/guide/topics/data/data-storage#filesInternal) 
而且日服pcr在启动时会检测root，一旦检测到会停止游戏启动。
虽然能用magisk等各种骚操作来回避掉，但不可能要求用户去这么做。

**Comment by lmhstcscr** [comment]
> 参考 [官方文档](https://developer.android.google.cn/guide/topics/data/data-storage#filesInternal)
> 而且日服pcr在启动时会检测root，一旦检测到会停止游戏启动。
> 虽然能用magisk等各种骚操作来回避掉，但不可能要求用户去这么做。

嗯嗯，不可能要root权限的，想得太简单了，感谢大佬!
