### ISSUE TITLE
关于更新数据库之后闪退

### ISSUE THREAD

**Issue by Louis-ui** [MalitsPlus/ShizuruNotes#36]
手机：一加7pro
android版本：android10
静流笔记版本：1.2.0
复现条件：清除储存和缓存后，进入设置里更新数据库

**Comment by chneqi** [comment]
我也更新后闪退，log如下

************* Log Head ****************
Date of Log        : 2020_12_31
Device Manufacturer: LGE
Device Model       : LM-V500N
Android Version    : 10
Android SDK        : 29
App VersionName    : 1.2.0
App VersionCode    : 29
************* Log Head ****************

17:27:18.639 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFile(FileUtils.java:99)]: FileNotExists: /data/user/0/com.github.malitsplus.shizurunotes/files/userData.json
17:27:18.715 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFileAndSize(FileUtils.java:119)]: /data/user/0/com.github.malitsplus.shizurunotes/databases/redive_jp.db. Size: 13012KB.

**Comment by MalitsPlus** [comment]
请升级到1.2.1版本以上，已修复闪退问题
