### ISSUE TITLE
how to install this app, i don't unterstand

### ISSUE THREAD

**Issue by kongmkm** [MalitsPlus/ShizuruNotes#40]
can you explain me ? i already downloaded but app has error can't access

**Comment by vuvuongthin** [comment]
you should delete old files and redownload apk file in this link: https://github.com/MalitsPlus/ShizuruNotes/releases

**Comment by kongmkm** [comment]
> you should delete old files and redownload apk file in this link: https://github.com/MalitsPlus/ShizuruNotes/releases

ok i can fix it. thank you so much
