### ISSUE TITLE
Database is not updating

### ISSUE THREAD

**Issue by AruJane** [MalitsPlus/ShizuruNotes#41]
![Screenshot_20210303_192037_com github malitsplus shizurunotes](https://user-images.githubusercontent.com/79990777/109829385-84aaa000-7c4e-11eb-99a0-da5f55a177a0.jpg)
Database is not updating. Tried to reinstall apk but it didn't help

**Comment by MalitsPlus** [comment]
This must be caused by database version was updated while database file did not. 
I added a new feature in version 1.3.0 try to solve issue #37 , but it seems this caused another issue uhmm... 

I will remove this feature in the next release to prevent users from misunderstanding.
