### ISSUE TITLE
部分角色，技能公式选择“原始”时会闪退

### ISSUE THREAD

**Issue by chneqi** [MalitsPlus/ShizuruNotes#42]
查看水狗时，技能公式却换到原始会闪退。
新出的切噜也会
不是所有角色都会闪退。

日志如下
************* Log Head ****************
Date of Log        : 2021_04_05
Device Manufacturer: LGE
Device Model       : LM-V500N
Android Version    : 10
Android SDK        : 29
App VersionName    : 1.4.3
App VersionCode    : 38
************* Log Head ****************

17:47:18.679 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFile(FileUtils.java:102)]: FileNotExists: /data/user/0/com.github.malitsplus.shizurunotes/files/userData.json
17:47:18.718 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFileAndSize(FileUtils.java:122)]: /data/user/0/com.github.malitsplus.shizurunotes/databases/redive_jp.db. Size: 14052KB.

**Comment by MalitsPlus** [comment]
已修复
