### ISSUE TITLE
在国服环境下一点工会战就闪退

### ISSUE THREAD

**Issue by ChaosQiu** [MalitsPlus/ShizuruNotes#43]
版本1.5.0
数据库是5月5号最新版，一点公会战界面就会闪退，日志如下：
************* Log Head ****************
Date of Log        : 2021_05_07
Device Manufacturer: meizu
Device Model       : 16s
Android Version    : 9
Android SDK        : 28
App VersionName    : 1.5.0
App VersionCode    : 40
************* Log Head ****************

19:11:48.608 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFile(FileUtils.java:102)]: FileNotExists: /data/user/0/com.github.malitsplus.shizurunotes/files/userData.json
19:11:48.635 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFileAndSize(FileUtils.java:122)]: /data/user/0/com.github.malitsplus.shizurunotes/databases/redive_cn.db. Size: 6938KB.
19:12:01.840 I/UpdateManager [main, com.github.malitsplus.shizurunotes.common.UpdateManager$1.dbCheckUpdateCompleted(UpdateManager.kt:112)]: New db version202105050022 determined.
19:20:52.214 I/UpdateManager [main, com.github.malitsplus.shizurunotes.common.UpdateManager.downloadDB(UpdateManager.kt:308)]: Start download DB ver202105050022.
19:21:00.350 I/UpdateManager [main, com.github.malitsplus.shizurunotes.common.UpdateManager$1.dbDownloadCompleted(UpdateManager.kt:150)]: DB download finished.
19:21:00.371 D/FileDelete [Thread-7, com.github.malitsplus.shizurunotes.utils.FileUtils.deleteFile(FileUtils.java:92)]: Delete file /data/user/0/com.github.malitsplus.shizurunotes/databases/redive_cn.db
19:21:00.372 I/UpdateManager [Thread-7, com.github.malitsplus.shizurunotes.common.UpdateManager.doDecompress(UpdateManager.kt:357)]: Start decompress DB.
19:21:00.479 I/UpdateManager [main, com.github.malitsplus.shizurunotes.common.UpdateManager$1.dbUpdateCompleted(UpdateManager.kt:158)]: DB update finished.
19:21:04.074 E/getBeanListByRaw [Thread-11, com.github.malitsplus.shizurunotes.db.DBHelper.getBeanListByRaw(DBHelper.kt:277)]: no such table: clan_battle_map_data (code 1 SQLITE_ERROR): , while compiling: SELECT a.clan_battle_id,
                CASE
                WHEN a.lap_num_from = 1 THEN 1
                WHEN a.lap_num_from = 2 AND a.clan_battle_id <= 1009 THEN 2
                WHEN a.lap_num_from = 2 THEN 1
                WHEN a.lap_num_from = 4 THEN 2
                WHEN a.lap_num_from = 6 THEN 3
                WHEN a.lap_num_from = 11 THEN 3
                WHEN a.lap_num_from = 35 THEN 4
                ELSE 1 END 'phase'
                ,b1.wave_group_id 'wave_group_id_1'
                ,b2.wave_group_id 'wave_group_id_2'
                ,b3.wave_group_id 'wave_group_id_3'
                ,b4.wave_group_id 'wave_group_id_4'
                ,b5.wave_group_id 'wave_group_id_5'
                FROM clan_battle_map_data AS a
                JOIN clan_battle_boss_group AS b1 ON a.clan_battle_boss_group_id = b1.clan_battle_boss_group_id AND b1.order_num = 1
                JOIN clan_battle_boss_group AS b2 ON a.clan_battle_boss_group_id = b2.clan_battle_boss_group_id AND b2.order_num = 2
                JOIN clan_battle_boss_group AS b3 ON a.clan_battle_boss_group_id = b3.clan_battle_boss_group_id AND b3.order_num = 3
                JOIN clan_battle_boss_group AS b4 ON a.clan_battle_boss_group_id = b4.clan_battle_boss_group_id AND b4.order_num = 4
                JOIN clan_battle_boss_group AS b5 ON a.clan_battle_boss_group_id = b5.clan_battle_boss_group_id AND b5.order_num = 5
                WHERE 1=1
                AND a.clan_battle_id = 1014
                AND (a.lap_num_from <> a.lap_num_to OR a.rsl_unlock_lap = 1)
                ORDER BY a.clan_battle_id,a.lap_num_from DESC
| Stack Trace: [android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method), android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:910), android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:521), android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588), android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58), android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37), android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46), android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408), android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1347), com.github.malitsplus.shizurunotes.db.DBHelper.getBeanListByRaw(DBHelper.kt:274), com.github.malitsplus.shizurunotes.db.DBHelper.getClanBattlePhase(DBHelper.kt:769), com.github.malitsplus.shizurunotes.data.ClanBattlePeriod.<init>(ClanBattlePeriod.kt:25), com.github.malitsplus.shizurunotes.db.RawClanBattlePeriod.transToClanBattlePeriod(RawClanBattlePeriod.java:19), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:31), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:11), kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)]
19:21:04.075 E/IndexOutOfBoundsException:Index: 0, Size: 0 [Thread-11, com.github.malitsplus.shizurunotes.common.CrashManager.uncaughtException(CrashManager.kt:12)]: [java.util.ArrayList.get(ArrayList.java:437), com.github.malitsplus.shizurunotes.data.ClanBattlePeriod.<init>(ClanBattlePeriod.kt:30), com.github.malitsplus.shizurunotes.db.RawClanBattlePeriod.transToClanBattlePeriod(RawClanBattlePeriod.java:19), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:31), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:11), kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)]
19:21:05.292 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFile(FileUtils.java:102)]: FileNotExists: /data/user/0/com.github.malitsplus.shizurunotes/files/userData.json
19:21:05.313 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFileAndSize(FileUtils.java:122)]: /data/user/0/com.github.malitsplus.shizurunotes/databases/redive_cn.db. Size: 6948KB.
19:21:26.390 E/checkAppVersion [OkHttp https://raw.githubusercontent.com/..., com.github.malitsplus.shizurunotes.common.UpdateManager$checkAppVersion$1.onFailure(UpdateManager.kt:205)]: timeout
19:21:38.758 E/getBeanListByRaw [Thread-6, com.github.malitsplus.shizurunotes.db.DBHelper.getBeanListByRaw(DBHelper.kt:277)]: no such table: clan_battle_map_data (code 1 SQLITE_ERROR): , while compiling: SELECT a.clan_battle_id,
                CASE
                WHEN a.lap_num_from = 1 THEN 1
                WHEN a.lap_num_from = 2 AND a.clan_battle_id <= 1009 THEN 2
                WHEN a.lap_num_from = 2 THEN 1
                WHEN a.lap_num_from = 4 THEN 2
                WHEN a.lap_num_from = 6 THEN 3
                WHEN a.lap_num_from = 11 THEN 3
                WHEN a.lap_num_from = 35 THEN 4
                ELSE 1 END 'phase'
                ,b1.wave_group_id 'wave_group_id_1'
                ,b2.wave_group_id 'wave_group_id_2'
                ,b3.wave_group_id 'wave_group_id_3'
                ,b4.wave_group_id 'wave_group_id_4'
                ,b5.wave_group_id 'wave_group_id_5'
                FROM clan_battle_map_data AS a
                JOIN clan_battle_boss_group AS b1 ON a.clan_battle_boss_group_id = b1.clan_battle_boss_group_id AND b1.order_num = 1
                JOIN clan_battle_boss_group AS b2 ON a.clan_battle_boss_group_id = b2.clan_battle_boss_group_id AND b2.order_num = 2
                JOIN clan_battle_boss_group AS b3 ON a.clan_battle_boss_group_id = b3.clan_battle_boss_group_id AND b3.order_num = 3
                JOIN clan_battle_boss_group AS b4 ON a.clan_battle_boss_group_id = b4.clan_battle_boss_group_id AND b4.order_num = 4
                JOIN clan_battle_boss_group AS b5 ON a.clan_battle_boss_group_id = b5.clan_battle_boss_group_id AND b5.order_num = 5
                WHERE 1=1
                AND a.clan_battle_id = 1014
                AND (a.lap_num_from <> a.lap_num_to OR a.rsl_unlock_lap = 1)
                ORDER BY a.clan_battle_id,a.lap_num_from DESC
| Stack Trace: [android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method), android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:910), android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:521), android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588), android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58), android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37), android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46), android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408), android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1347), com.github.malitsplus.shizurunotes.db.DBHelper.getBeanListByRaw(DBHelper.kt:274), com.github.malitsplus.shizurunotes.db.DBHelper.getClanBattlePhase(DBHelper.kt:769), com.github.malitsplus.shizurunotes.data.ClanBattlePeriod.<init>(ClanBattlePeriod.kt:25), com.github.malitsplus.shizurunotes.db.RawClanBattlePeriod.transToClanBattlePeriod(RawClanBattlePeriod.java:19), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:31), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:11), kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)]
19:21:38.760 E/IndexOutOfBoundsException:Index: 0, Size: 0 [Thread-6, com.github.malitsplus.shizurunotes.common.CrashManager.uncaughtException(CrashManager.kt:12)]: [java.util.ArrayList.get(ArrayList.java:437), com.github.malitsplus.shizurunotes.data.ClanBattlePeriod.<init>(ClanBattlePeriod.kt:30), com.github.malitsplus.shizurunotes.db.RawClanBattlePeriod.transToClanBattlePeriod(RawClanBattlePeriod.java:19), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:31), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:11), kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)]
19:21:40.121 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFile(FileUtils.java:102)]: FileNotExists: /data/user/0/com.github.malitsplus.shizurunotes/files/userData.json
19:21:40.144 I/FileCheck [main, com.github.malitsplus.shizurunotes.utils.FileUtils.checkFileAndSize(FileUtils.java:122)]: /data/user/0/com.github.malitsplus.shizurunotes/databases/redive_cn.db. Size: 6948KB.

**Comment by MalitsPlus** [comment]
应该是国服数据库结构终于改成跟日服一致了，明天就修。

**Comment by ChaosQiu** [comment]
已更新，现在公会战界面不会闪退了，那5月份公会战的数据还能读取吗

**Comment by MalitsPlus** [comment]
中午脑抽了（
1.6.2已恢复显示历史数据

**Comment by ChaosQiu** [comment]
已解决，感谢您的支持与帮助
