### ISSUE TITLE
Calendar Timezone

### ISSUE THREAD

**Issue by Blazewardog** [MalitsPlus/ShizuruNotes#44]
Can the calendar display be shown in the selected server's Timezone? The way it works currently is it shows the date of the phone not the server. 

This leads to usually being a day behind when looking at the calendar for JP in the US.

**Comment by MalitsPlus** [comment]
Okay, I'll come up with a solution in a few days.

**Comment by Blazewardog** [comment]
Looks like it is working from USA => Japan Server.
