### ISSUE TITLE
国服地下城炸了（v1.12.0）

### ISSUE THREAD

**Issue by lkct** [MalitsPlus/ShizuruNotes#49]
no such table: dungeon_area，stack trace指向：
https://github.com/MalitsPlus/ShizuruNotes/blob/5f54c3b41ad291b2e72666324f8a57038498d76f/app/src/main/java/com/github/malitsplus/shizurunotes/db/DBHelper.kt#L1145-L1174

看上去是日服加了ex5之后新的数据库和国服不兼容了

**Comment by MalitsPlus** [comment]
是我忽略了，已修复
