### ISSUE TITLE
可以考虑支持Android 7.1.1+吗

### ISSUE THREAD

**Issue by Yanstory** [MalitsPlus/ShizuruNotes#5]
毕竟Android 7.1.1的设备还是挺多的

**Comment by MalitsPlus** [comment]
刚创建项目的时候最低SDK我设的25（Android 7），后来开发过程中发现一些新特性低版本不支持又懒得找其他兼容低版本的方法才改成现在这样的。

**Comment by Yanstory** [comment]
这样啊😥

**Comment by MalitsPlus** [comment]
嗯，而且我手上目前只有Android 8和10两个手机，就算支持7.1.1也没法进行实机调试。
7.1.1已经算比较老的系统了吧，建议升级一下（

**Comment by MakiseKurisu** [comment]
雷电模拟器现在只支持7.1.2该如何升级...
