### ISSUE TITLE
[Request/Question] Adding the rest of the events

### ISSUE THREAD

**Issue by 64BTX** [MalitsPlus/ShizuruNotes#54]
Looks like when loading the Events tab in the app, it only has the events from the past year + the Re:Zero and Idolm@ster events. Is it possible to have all the events from the first one included (as well as the April 1st ones), or is it just not available wherever the app gets the database? Thanks!

**Comment by MalitsPlus** [comment]
Well, this issue has actually existed for a long time but, since no one ever mentioned it I just put it aside. 
Now finally, you mentioned it, I think I must do my work then. 
I will fix it before the next release.
