### ISSUE TITLE
ホマレ's unknown skill target

### ISSUE THREAD

**Issue by HerDataSam** [MalitsPlus/ShizuruNotes#55]
I found that ホマレ's target of IfForChildAction (UB Action 1 and 3, Skill 1 Action 2, and Skill 2 Action 1) is Unknown.

This issue comes from the wrong exception handling of `ifType` where you have assigned as `IfType.unknown` in line 125 in the `IfForChildAction`.
Her skill's target is not affected by the `action_detail_1` but `target_type` as you handled. 

Please consider the change below on both line 18 and line 43. 

```diff
-    if(ifType != null) {
+    if(ifType != IfType.unknown) {
```

I already changed this to my forked project and it works well.

https://github.com/HerDataSam/KasumiNotes/commit/693038623ced1292942fa68b2333972edf9d30d1#diff-1ac07a801dee23cade0865922d03c2d6889be3c9bac6c5e9b440ae19ba323f55

**Comment by MalitsPlus** [comment]
Ah thanks, I haven't noticed this until you told me. 
Besides, if you already has a solution you can definitely open a PR rather than an issue instead :)

**Comment by HerDataSam** [comment]
Oh, that way is better. I have not thought about that because your project and my project are a lot different. 
I will use Pull Requests next time. At this time, please fix the issue accordingly. :)
