### ISSUE TITLE
国服数据初始化失败

### ISSUE THREAD

**Issue by lkct** [MalitsPlus/ShizuruNotes#57]
```
17:28:33.446 E/loadCharaData [Thread-7, com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelChara$loadData$1.invoke(SharedViewModelChara.kt:57)]: Text '2022/4/17 11:00' could not be parsed at index 5
```
我看了下数据库，其他的时间格式应该都是`2022/04/25 11:00:00`这样，但是春妈时间写成了`2022/4/17 11:00`。

**Comment by MalitsPlus** [comment]
感谢反馈，已修复

**Comment by paulzzh** [comment]
同样的问题造成公会战页面无法打开

<details>
12:57:51.821 E/DateTimeParseException:Text '2023/1/26 5:00:00' could not be parsed at index 5 [Thread-6, com.github.malitsplus.shizurunotes.common.CrashManager.uncaughtException(CrashManager.kt:12)]: [java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2044), java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1946), java.time.LocalDateTime.parse(LocalDateTime.java:486), com.github.malitsplus.shizurunotes.db.RawClanBattlePeriod.transToClanBattlePeriod(RawClanBattlePeriod.java:18), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:32), com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:29), kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)]
</details>

https://github.com/paulzzh/redive_cn_master_db_diff/blob/46e0bee8e62578c8f8b1138982fb3bf7f5800e31/clan_battle_schedule.sql#L36
