### ISSUE TITLE
建议增加角色搜索功能

### ISSUE THREAD

**Issue by yuudi** [MalitsPlus/ShizuruNotes#6]
有时候想找一个角色挺费事的，建议增加角色搜索功能。

P.S.
这个昵称表也许有帮助<https://gitee.com/yobot/pcr-nickname/blob/master/nicknames.csv>

**Comment by MalitsPlus** [comment]
其实我也在考虑想加一个角色检索功能，等把rank对比功能做完之后搞一个

**Comment by MalitsPlus** [comment]
ver1.0.0已追加
