### ISSUE TITLE
Char details not displaying with latest download

### ISSUE THREAD

**Issue by Gkj1213** [MalitsPlus/ShizuruNotes#60]
![Screenshot_20220708-112237_ShizuruNotes](https://user-images.githubusercontent.com/52625073/177910821-2fc55323-0394-40c3-9975-f0a8383bdde8.jpg)
![Screenshot_20220708-112736_ShizuruNotes](https://user-images.githubusercontent.com/52625073/177911223-c12975da-1e28-410a-8e5d-e7aaa102d34d.jpg)
![Screenshot_20220708-112251_ShizuruNotes](https://user-images.githubusercontent.com/52625073/177910816-31ec1670-cd83-4bd3-89b1-7f34a20ecf17.jpg)

Device: Samsung Galaxy M31
Android version: 12

Database version: 10039700
Application version: 1.15.2

Hitting some issues where character information is not displaying after the latest database download.

**Comment by MightyZanark** [comment]
Seems like this is because for whatever reason the `unique_equipment_enhance_rate` table doesn't have the new UE for SEriko and SShizuru, but the other relevant tables have it

**Comment by MalitsPlus** [comment]
Thx for reporting. 
It has been [fixed](https://github.com/MalitsPlus/ShizuruNotes/commit/968b23cf2953cb86cb8dbe6af551e9f0579eb8ac) since version 1.16.0.

**Comment by MalitsPlus** [comment]
> > Thx for reporting. It has been [fixed](https://github.com/MalitsPlus/ShizuruNotes/commit/968b23cf2953cb86cb8dbe6af551e9f0579eb8ac) since version 1.16.0.
> 
> 直接改表名破坏了国服数据库兼容性 现在的版本无法显示国服数据

草（草
