### ISSUE TITLE
公会战页面无法打开

### ISSUE THREAD

**Issue by paulzzh** [MalitsPlus/ShizuruNotes#61]
先上日志：[pastebin](https://pastebin.com/W89aQVDa) 

大概是这次只更新了一行 clan_battle_period https://github.com/esterTion/redive_master_db_diff/commit/2e61575c236f46b757ef6da90e21d07f3bd80c27#diff-4f7cf1d206a1ebb6b32dccb7030e19d67feb15902fcb5df4f778a257026f88bbL53

没有更新 clan_battle_2_map_data 的boss数据

但是从clan_battle_period读到clan_battle_id之后就会clan_battle_2_map_data里找所以就炸了（）

**Comment by MalitsPlus** [comment]
> 但是从clan_battle_period读到clan_battle_id之后就会clan_battle_2_map_data里找所以就炸了（）

倒不是这个原因，因为空数据会自动被跳过。

主要是初始化的时候断定了phaseList不为空，加一个[检测](https://github.com/MalitsPlus/ShizuruNotes/blob/450f3bf2815eafd5b2acf86717f126573e9a2aa8/app/src/main/java/com/github/malitsplus/shizurunotes/data/ClanBattlePeriod.kt#L30)就行了。
