### ISSUE TITLE
Missing stats from ranks for summons

### ISSUE THREAD

**Issue by MightyZanark** [MalitsPlus/ShizuruNotes#63]
On Ranpha's release, the showcase video on Twitter showed that her summon (id 418101) can deal a critical hit, but Shizuru Notes does not show this info. And after a quick dig at the database, I found that the summon gets some stats from ranks (HP, ATK, DEF, etc), which is also not reflected in the summon info page. This is also true for Neneka's clone. 

So is it possible to make it so the rank stats from the `unit_promotion_bonus` table for summons gets added to the summons stat page? I'm not experienced enough to try and make a pull request for this type of thing so I can only submit this issue.

**Comment by MalitsPlus** [comment]
> I found that the summon gets some stats from ranks (HP, ATK, DEF, etc), which is also not reflected in the summon info page.

Ah, never thought a summon can be affected by the summoner's rank, I'll make this fixed soon. 
Btw summons get no benefits from `promotion_bonus` which only gives characters extra stats when they stay in the heighest 2 ranks. 

> her summon (id 418101) can deal a critical hit, but Shizuru Notes does not show this info.

This is a feature. Statuses like Critical for summons are not as important as they are for characters hence there would be few people care about it (after all it is just a coin flip game). For the purpose of making Minion Info UI as brief as possible I didn't make those stats show on the screen, although there is no harm in showing them.

**Comment by MightyZanark** [comment]
> This is a feature. Statuses like Critical for summons are not as important as they are for characters hence there would be few people care about it (after all it is just a coin flip game). For the purpose of making Minion Info UI as brief as possible I didn't make those stats show on the screen, although there is no harm in showing them.

I see, that's a fair point. You can leave it as is then since yea there's only a limited number of minions that can actually crit.

And thanks for fixing the rank stats for summons!
