### ISSUE TITLE
Bugged skill action for Halloween Nanaka

### ISSUE THREAD

**Issue by Wazhai** [MalitsPlus/ShizuruNotes#64]
Halloween Nanaka's skill 2 simply applies an 80% debuff to HP recovery boost according to the in-game description as well as every other source I checked [such as this](https://docs.google.com/spreadsheets/d/1JjK7Ws4gfzKChRs5ueoxEZVN5SXK10nhDC1-nbm0NUs/edit). The app shows something completely different and much more powerful.
![Screenshot_20221019-140638_ShizuruNotes](https://user-images.githubusercontent.com/14195241/196691097-7fcd66a8-a292-4bb2-a474-ebcdf1165520.jpg)
![Screenshot_20221019-142507_PrincessConnectRedive](https://user-images.githubusercontent.com/14195241/196691105-f6bef738-ff0c-48ad-b781-cdd0f899ca07.jpg)

**Comment by MalitsPlus** [comment]
Fixed at 1.18.0

**Comment by Wazhai** [comment]
Great, thanks
