### ISSUE TITLE
enemy_id 401511504 Has New Skill

### ISSUE THREAD

**Issue by krulci** [MalitsPlus/ShizuruNotes#67]
11月DE4的Main 2的action 5有新技能
![image](https://user-images.githubusercontent.com/52474054/203177815-055a2601-6781-4c85-ae4e-486b6ac7403b.png)
![image](https://user-images.githubusercontent.com/52474054/203182212-ffc6aa99-0a41-49a7-bcea-83e7b61a1882.png)

98是應該是減TP

**Comment by MalitsPlus** [comment]
前几天有点忙没来得及修，已更新。

**Comment by krulci** [comment]
> 前几天有点忙没来得及修，已更新。 

感谢，就等着你更新我抄成C#用...

**Comment by MalitsPlus** [comment]
> 感谢，就等着你更新我抄成C#用...

？？？你上面那个图不是已经有了

**Comment by krulci** [comment]
> > 感谢，就等着你更新我抄成C#用...
> 
> 
> 
> ？？？你上面那个图不是已经有了 

https://github.com/cc004/ActionParameterSerializer

**Comment by MalitsPlus** [comment]
游戏源码都逆出来了不就能照着抄了吗（

**Comment by krulci** [comment]
> 游戏源码都逆出来了不就能照着抄了吗（ 

技能描述的string不是你自己加的？

**Comment by MalitsPlus** [comment]
哦…我明白了
