### ISSUE TITLE
Update for calendar logic

### ISSUE THREAD

**Issue by Wazhai** [MalitsPlus/ShizuruNotes#68]
The beginner bonus campaign has been implemented as a permanently ongoing drop campaign that appears in the app calendar until the year 2032.

Official details: https://priconne-redive.jp/news/update/20375/

![Screenshot_20221215_084734_ShizuruNotes](https://user-images.githubusercontent.com/14195241/207807360-b029e047-c6cf-439d-b3ce-1ef739c32e8a.png)

It seems best to ignore these beginner-specific entries in the calendar because they won't apply to anyone over level 200 and result in misleading entries being shown.

**Comment by MalitsPlus** [comment]
Fixed at v1.20.0

**Comment by Wazhai** [comment]
Something doesn't seem right because after the update, the currently ongoing 3x drop campaigns for all players also disappeared from the calendar.

![Screenshot_20221216_101636_ShizuruNotes](https://user-images.githubusercontent.com/14195241/208070520-caec66b1-8913-4411-a1f5-2af22f15cf00.png)

![Screenshot_20221216_104816_Twitter](https://user-images.githubusercontent.com/14195241/208071377-03bcf7ef-4811-4c62-9014-86514e2ab69b.png)

**Comment by MalitsPlus** [comment]
My fault. Didn't notice some campaigns are only for higher level players.

**Comment by paulzzh** [comment]
> My fault. Didn't notice some campaigns are only for higher level players.

最近两次更新后 国服的日历也不正常了 调查2探索2困难2啥的全都不显示了

**Comment by MalitsPlus** [comment]
又忘了向下兼容国服…

**Comment by MightyZanark** [comment]
I think you can filter by `id` instead of `lv_to`. For the new beginner campaigns from what I can see, they start from `id 5001`, and the usual campaigns are still around `id 1507`. This `id` filter should work across all different servers.
