### ISSUE TITLE
日服12月四五阶段4王技能3的TP减少效果应该为50%不是0.5%

### ISSUE THREAD

**Issue by sioisan** [MalitsPlus/ShizuruNotes#69]
![image](https://user-images.githubusercontent.com/18576604/209130465-6277601b-5ef6-4a50-a69b-481b9923af20.png)
![image](https://user-images.githubusercontent.com/18576604/209130517-2f226a02-1241-4132-8ce9-6f1131eca4a3.png)

**Comment by MalitsPlus** [comment]
已修复。
但构建依赖的 [Jitpack 仓库目前处于爆炸状态](https://github.com/jitpack/jitpack.io/issues/5337)，得等到那边修复之后才能发布（
