### ISSUE TITLE
Potentially new campaign IDs introduced for 5x drops

### ISSUE THREAD

**Issue by Wazhai** [MalitsPlus/ShizuruNotes#73]
rwiki already lists 5x drops for JP 5th anniversary campaigns, but this isn't appearing in the ShizuruNotes calendar. Could this be newly introduced campaign IDs it can't parse yet?

https://rwiki.jp/priconne_redive/%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%9A%E3%83%BC%E3%83%B3

**Comment by MalitsPlus** [comment]
Doesn't seem like that. 
Has had a glance at the [database](https://github.com/esterTion/redive_master_db_diff/blob/master/campaign_schedule.sql), they haven't added anniversary campaigns into schedule table yet. Stay patient bro.

**Comment by Wazhai** [comment]
Ok, thanks and sorry for bothering you! I only wanted to mention this possibility just in case. It's strange for campaign info to appear so early and so far ahead. Rwiki might be wrong and doing predictions/guesswork.

Still worth keeping an eye out if everything in the calendar works correctly in the next weeks
