### ISSUE TITLE
新技能效果

### ISSUE THREAD

**Issue by sioisan** [MalitsPlus/ShizuruNotes#74]
2023年2月公会战三-五阶段BOSS-5技能1效果4
![image](https://user-images.githubusercontent.com/18576604/219658784-11508c75-08d8-477f-ad82-ad0b94d17ee8.png)

黑骑六星UB效果3
![image](https://user-images.githubusercontent.com/18576604/219658738-46d7c95d-c6d4-485c-8580-a0d27e89cb16.png)

**Comment by MalitsPlus** [comment]
已修复。
