### ISSUE TITLE
专武260级以上的数据不正确

### ISSUE THREAD

**Issue by csga31971** [MalitsPlus/ShizuruNotes#75]
260级以后tp上升和tp减轻不再增加，会额外增加其他属性
拿泳装配可举例，游戏内270级专武的属性是1160攻击力/362暴击/14tp减轻，app里是1156攻击力/362暴击/15tp减轻

**Comment by MalitsPlus** [comment]
应该好了。
不过我只确认了这里给出的泳装配可专武参数是正确的，其他的没有确认过（没有261以上的专武），如果看到其他角色的专武参数有误请在下面回复。
