### ISSUE TITLE
装备多选最多只能选5个，但我希望更多

### ISSUE THREAD

**Issue by LinXueyuanStdio** [MalitsPlus/ShizuruNotes#8]
在计划刷装备的时候，希望找出能最大覆盖所需装备的关卡，这样就算掉落歪了，也能有较大的概率歪到次要的所需装备上，减少刷图次数。

目前只能最多选5个装备。但是，我希望可以选中的装备个数没有上限。。。

**Comment by MalitsPlus** [comment]
其实静流笔记的掉落检索算法辣鸡得我自己都不忍看，本身的设计目的就是养老期偶尔有残余量少的装备搜一下刷刷图，不适合大量检索。
需要大量检索的话建议使用兰德索尔图书馆的工具，强大得多，还能帮你规划最优的刷图路线，我就不重复造轮子了。
