### ISSUE TITLE
611更新咯

### ISSUE THREAD

**Issue by Fangliding** [MalitsPlus/ShizuruNotes#81]
未知效果(绝望)
而且六星后两个技能估计也得单独开地方

**Comment by MalitsPlus** [comment]
> 而且六星后两个技能估计也得单独开地方

没看懂什么意思？

**Comment by Fangliding** [comment]
> > 而且六星后两个技能估计也得单独开地方
> 
> 没看懂什么意思？

看错了 技能用加标记的方法改效果可还行()
