### ISSUE TITLE
会战BOSS闪退

### ISSUE THREAD

**Issue by sioisan** [MalitsPlus/ShizuruNotes#84]
### 日志
`************* Log Head ****************
Date of Log        : 2023_07_22
Device Manufacturer: Xiaomi
Device Model       : 22041216UC
Android Version    : 13
Android SDK        : 33
App VersionName    : 1.23.0
App VersionCode    : 102
************* Log Head ****************

12:42:07.712 E/NumberFormatException:For input string: "##系数1##0.8" [main, 
com.github.malitsplus.shizurunotes.common.CrashManager.uncaughtException(CrashManager.kt:12)]: [jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054), 
jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110), 
java.lang.Double.parseDouble(Double.java:543), 
com.github.malitsplus.shizurunotes.data.action.ChangeSpeedOverwriteFieldAction.localizedDetail(ChangeSpeedOverwriteFieldAction.java:59), 
com.github.malitsplus.shizurunotes.data.Skill.setActionDescriptions(Skill.kt:272), 
com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle.mSetSelectedBoss(SharedViewModelClanBattle.kt:71), 
com.github.malitsplus.shizurunotes.ui.clanbattle.clanbattledetails.adapters.ClanBattlePhaseAdapter.onBindViewHolder$lambda-1$lambda-0(ClanBattlePhaseAdapter.kt:44), 
com.github.malitsplus.shizurunotes.ui.clanbattle.clanbattledetails.adapters.ClanBattlePhaseAdapter.$r8$lambda$6uZgGLID9z_BSrWH8pXtPlpMJYU(Unknown Source:0), 
com.github.malitsplus.shizurunotes.ui.clanbattle.clanbattledetails.adapters.ClanBattlePhaseAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4), 
android.view.View.performClick(View.java:7560), 
android.view.View.performClickInternal(View.java:7533), 
android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0), 
android.view.View$PerformClick.run(View.java:29754), 
android.os.Handler.handleCallback(Handler.java:942), 
android.os.Handler.dispatchMessage(Handler.java:99), 
android.os.Looper.loopOnce(Looper.java:210), 
android.os.Looper.loop(Looper.java:299), 
android.app.ActivityThread.main(ActivityThread.java:8136), 
java.lang.reflect.Method.invoke(Native Method), 
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580), 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)]`

### 复现步骤

1. 切换服务器至日服
2. 选择任意角色，点击右上角切换技能公式至原始
3. 切换至公会战，选择2023年7月/阶段4/最下方BOSS（4阶段狮子）

**Comment by MalitsPlus** [comment]
感谢反馈，已修复
