### ISSUE TITLE
eActionType 101~106 & 901~902

### ISSUE THREAD

**Issue by krulci** [MalitsPlus/ShizuruNotes#85]
能不能把这几个加上？
![image](https://github.com/MalitsPlus/ShizuruNotes/assets/52474054/f13c0a3e-3be8-4797-b4e3-4cceb62494b4)

**Comment by MalitsPlus** [comment]
上游从 7.1.0 开始就停止解析了，似乎是因为 DMM 端的动态链接库改用 il2cpp 而抛弃了以前从 C# 直接编译导致的，所以从那之后新增的技能我这边都看不到了。

**Comment by krulci** [comment]
> 上游从 7.1.0 开始就停止解析了，似乎是因为 DMM 端的动态链接库改用 il2cpp 而抛弃了以前从 C# 直接编译导致的，所以从那之后新增的技能我这边都看不到了。

你需要什么才能更新？
我把打包好的IDA数据库发你能用吗？
或者你这词条是用什么逻辑写的？
我之后都是照抄到C#，但是不太理解你这个词条是怎么写的

**Comment by MalitsPlus** [comment]
> 你需要什么才能更新？
> 我把打包好的IDA数据库发你能用吗？

IDA 反编译出来的只是 C 的伪码，虽然理论上可以凭毅力去解读但太费时间。

> 或者你这词条是用什么逻辑写的？

至今为止的词条都是直接用 dnspy 反编译 DMM 端的 DLL（当时 DMM 端还没有用 il2cpp），直接就能得到近乎游戏源码水平的逻辑，然后通过解读这些逻辑写的。

**Comment by krulci** [comment]
> > 你需要什么才能更新？
> 
> > 我把打包好的IDA数据库发你能用吗？
> 
> 
> 
> IDA 反编译出来的只是 C 的伪码，虽然理论上可以凭毅力去解读但太费时间。
> 
> 
> 
> > 或者你这词条是用什么逻辑写的？
> 
> 
> 
> 至今为止的词条都是直接用 dnspy 反编译 DMM 端的 DLL（当时 DMM 端还没有用 il2cpp），直接就能得到近乎游戏源码水平的 C# 逻辑，然后通过解读这些逻辑写的。

我的意思是说，我比对了之前的几个技能类型，但是没理解你是怎么造句的。 
比如UnableStateGaurdAction的这个string format的<string name="Enable_s1_to_resist_all_sorts_of_incapacity_efficacies_up_to_s2_times_in_a_period_of_s3_sec">使%1$s免疫所有控制效果，最大 [%2$s] 次，持续时间 [%3$s] 秒。</string>
这个是如何知道要这么造的，还有数值的对应
这个对照以前mono版本的代码也没看有这个string format啊

**Comment by MalitsPlus** [comment]
> 这个是如何知道要这么造的，还有数值的对应

上面说了 “得到近乎游戏源码水平的 C# 逻辑，然后通过解读这些逻辑写的”。

> 这个对照以前mono版本的代码也没看有这个string format啊

游戏源码里没有 string format，我解读是通过各个技能继承 `ActionParameter` 这个超类的 `ExecAction()` 和 `SetLevel()` 里边各个对应数值的处理逻辑来写的。
另外以前的 DMM 端连 mono 都没有用，是直接从 C# 编译的。

> 但是你应该可以用CPP2IL

ACK。有空去研究一下。

**Comment by krulci** [comment]
> > 这个是如何知道要这么造的，还有数值的对应
> 
> 
> 
> 上面说了 “得到近乎游戏源码水平的 C# 逻辑，然后通过解读这些逻辑写的”。
> 
> 
> 
> > 这个对照以前mono版本的代码也没看有这个string format啊
> 
> 
> 
> 游戏源码里没有 string format，我解读是通过各个技能继承 `ActionParameter` 这个超类的 `ExecAction()` 和 `SetLevel()` 里边各个对应数值的处理逻辑来写的。
> 
> 另外以前的 DMM 端连 mono 都没有用，是直接从 C# 编译的。
> 
> 
> 
> > 但是你应该可以用CPP2IL
> 
> 
> 
> ACK。有空去研究一下。

以前一直就是mono的啊
Unity只有mono和il2cpp
Managed的代码几乎都在Assembly-CSharp
就一些加密的和数据库相关的搞成了native而已
Managed代码只是隐藏了要从运行时dump出来

**Comment by MalitsPlus** [comment]
目前还有一种邪道方式是，可以直接去读数据库参数，再根据游戏里的技能描述来猜各个参数的作用，然后写成自己的逻辑。
但这种方式毕竟脱离了游戏源码，容易出错，所以我没有打算用这种方式。

**Comment by MalitsPlus** [comment]
> Managed代码只是隐藏了要从运行时dump出来

我对 unity 不熟不太了解，也就是说现在也能够 dump 出 dnspy 可读的 IL 代码？

**Comment by krulci** [comment]
> > Managed代码只是隐藏了要从运行时dump出来
> 
> 
> 
> 我对 unity 不熟不太了解，也就是说现在也能够 dump 出 IL 代码？

Cpp2Il这项目就是在搞这个的，把native的GameAssembly.dll还原成IL，然后就能用IlSpy或者DnSpy解读。 
但是我记得这游戏搞了偏移，要用的话应该要自己调一下偏移。 
我改dmm是用的il2cppdumper的指针偏移逻辑来获得指针的C# wrapper的

**Comment by MalitsPlus** [comment]
> Cpp2Il这项目就是在搞这个的，把native的GameAssembly.dll还原成IL，然后就能用IlSpy或者DnSpy解读。
> 但是我记得这游戏搞了偏移，要用的话应该要自己调一下偏移。

去试了一下，还不止这个问题，metadata 也藏起来了。等有空再搞算了（摸

**Comment by krulci** [comment]
如果我错了请纠正我
`childInit`是根据`SetLevel`

> > Cpp2Il这项目就是在搞这个的，把native的GameAssembly.dll还原成IL，然后就能用IlSpy或者DnSpy解读。
> > 但是我记得这游戏搞了偏移，要用的话应该要自己调一下偏移。
> 
> 去试了一下，还不止这个问题，metadata 也藏起来了。等有空再搞算了（摸

https://github.com/krulci/PrincessDumper
我这个可以直接dump

**Comment by krulci** [comment]
> 目前还有一种邪道方式是，可以直接去读数据库参数，再根据游戏里的技能描述来猜各个参数的作用，然后写成自己的逻辑。
> 但这种方式毕竟脱离了游戏源码，容易出错，所以我没有打算用这种方式。

如果能直接debug呢？
就是直接hook `SetLevel`和`ExecAction`然后把参数log出来看

**Comment by MalitsPlus** [comment]
> childInit是根据SetLevel

大致上是的。

> 如果能直接debug呢？
> 就是直接hook SetLevel和ExecAction然后把参数log出来看

那样最多只能够看一下输入和输出，关键的数据库中各个参数的处理逻辑还是在函数内部。

**Comment by krulci** [comment]
> > childInit是根据SetLevel
> 
> 大致上是的。
> 
> > 如果能直接debug呢？
> > 就是直接hook SetLevel和ExecAction然后把参数log出来看
> 
> 那样最多只能够看一下输入和输出，关键的数据库中各个参数的处理逻辑还是在函数内部。
弄出来了，虽然不是很准确，可能需要自己对照下IDA或Ghidra，但是能大概看出他的逻辑。
这样的能继续更吗？
![image](https://github.com/MalitsPlus/ShizuruNotes/assets/52474054/5d97ab8b-6ada-415f-ad93-f32cd9fc223c)

**Comment by MalitsPlus** [comment]
> 弄出来了，虽然不是很准确，可能需要自己对照下IDA或Ghidra，但是能大概看出他的逻辑。
> 这样的能继续更吗？

我可以试试，能把这个 Class 的全内容分享一下吗？

另外之前我说的

> 我解读是通过各个技能继承 `ActionParameter` 这个超类的 `ExecAction()` 和 `SetLevel()` 里边各个对应数值的处理逻辑

不太准确，这是最简单的情况。如果类里边还有其他方法（比如这张图里的 `ExecActionOnStart` 和 `ReadyAction`）根据情况也需要解读。

**Comment by krulci** [comment]
> > 弄出来了，虽然不是很准确，可能需要自己对照下IDA或Ghidra，但是能大概看出他的逻辑。
> > 这样的能继续更吗？
> 
> 我可以试试，能把这个 Class 的全内容分享一下吗？
> 
> 另外之前我说的
> 
> > 我解读是通过各个技能继承 `ActionParameter` 这个超类的 `ExecAction()` 和 `SetLevel()` 里边各个对应数值的处理逻辑
> 
> 不太准确，这是最简单的情况。如果类里边还有其他方法（比如这张图里的 `ExecActionOnStart` 和 `ReadyAction`）根据情况也需要解读。

你有QQ或Discord吗？我把DLL打包和IDA打包给你，你直接看？

**Comment by MalitsPlus** [comment]
> 你有QQ或Discord吗？

emmm... 我不太用这两个软件。可以 Telegram 或者直接 `curl --upload-file xxx.zip https://transfer.sh`

> 我把DLL打包和IDA打包给你

DLL 就够了，IDA 太大了而且也看不懂（

**Comment by krulci** [comment]
> https://transfer.sh

https://transfer.sh/%28/STrnQkKJxf/priconner%204.1.0%20Android_TW.7z%29.zip
Arm64的效果还是不好
要好点效果还是要用DMM版本的

**Comment by MalitsPlus** [comment]
试着解读了一下，搞不定。

我找了一个现有的做比较，比如 `UnableStateGuardAction`，原本长这个样子：

```cs
public override void SetLevel(float _level)
{
  base.SetLevel(_level);
  base.Value[eValueNumber.VALUE_1] = (float)(base.MasterData.action_value_1 + base.MasterData.action_value_2 * (double)_level);
  base.Value[eValueNumber.VALUE_3] = (float)(base.MasterData.action_value_3 + base.MasterData.action_value_4 * (double)_level);
}
```

从 DLL 中反编译出来长这个样子：

```cs
public override void SetLevel(float _level)
{
  MasterSkillAction.SkillAction <MasterData>k__BackingField = this.<MasterData>k__BackingField;
  Dictionary<eValueNumber, float> <Value>k__BackingField = this.<Value>k__BackingField;
  if (<MasterData>k__BackingField == null)
  {
  }
  MasterSkillAction.SkillAction <MasterData>k__BackingField2 = this.<MasterData>k__BackingField;
  MasterSkillAction.SkillAction <MasterData>k__BackingField3 = this.<MasterData>k__BackingField;
  Dictionary<eValueNumber, float> <Value>k__BackingField2 = this.<Value>k__BackingField;
  MasterSkillAction.SkillAction <MasterData>k__BackingField4 = this.<MasterData>k__BackingField;
}
```

看不出来参数是怎么计算的，乘的那个 `_level` 也消失了。

**Comment by cc004** [comment]
我对着ida给101~108写了一下，可以参考着搞一下
https://github.com/cc004/ActionParameterSerializer/pull/1

**Comment by MalitsPlus** [comment]
v1.27.0 已追加新技能描述
有问题欢迎提 issue
