### ISSUE TITLE
动作数量超过10的潜在bug

### ISSUE THREAD

**Issue by cc004** [MalitsPlus/ShizuruNotes#86]
更新action数量后，代码中富含的`action = detail % 10`应该都有可能出bug

https://github.com/MalitsPlus/ShizuruNotes/blob/069866b32b770bd40fb47163a1a1c620c55f424b/app/src/main/java/com/github/malitsplus/shizurunotes/data/action/IfForAllAction.java#L21-L29

**Comment by MalitsPlus** [comment]
感谢反馈。
目前把搜到的都替换掉了，可能还有一小部分不容易发现的漏网之鱼，只有等出问题的时候再补救了。
