### ISSUE TITLE
github 经常超时

### ISSUE THREAD

**Issue by PHINEXLISY** [MalitsPlus/ShizuruNotes#88]
如果超时，可以试一下备用链接，免费cdn [jsDelivr](https://www.jsdelivr.com/)

你的仓库：[https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes/](https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes/)

你的更新日志：[https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes@master/update_log.json](https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes@master/update_log.json)

这是官方使用参考：[https://www.jsdelivr.com/?docs=gh](https://www.jsdelivr.com/?docs=gh)

**Comment by PHINEXLISY** [comment]
另外我看干炸里脊店里图片资源加载很吃力，可以使用一个git分支用作图片分钟，用上述方法jsdelivr cdn

**Comment by PHINEXLISY** [comment]
干炸里脊店的图片可以用同样方法白嫖上述cdn

**Comment by MalitsPlus** [comment]
感谢建议。

> 你的更新日志：https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes@master/update_log.json

除了作为静态数据的 JSON，作为接口交换的 JSON 数据是不应该使用 cache 的。

不过把接口数据放在 repo 里也确实不是什么好做法，目前静流笔记的流量完全可以白嫖 worker KV 和 firebase 之类的免费额度，只不过从建立到现在没出什么大岔子我就偷懒没改了......

> 干炸里脊店的图片可以用同样方法白嫖上述cdn

干炸里脊那边的资源现在已经是通过 cf cache 过的，没有必要再弄。

**Comment by PHINEXLISY** [comment]
cf也是同样对大陆不友好，直接用也问题不大。

不过我认为

> 作为接口交换的 JSON 数据是不应该使用 cache 

使用cdn不等于使用cache，对于不需要cache的数据，
①第一个办法也是最常用的办法，可以使用`Cache-Control`请求头控制。
②可以使用cf的`worker+CNAME`反代[https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes/](https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes/)，然后使用cf的`Cache Rules`控制不cache，既可以利用jsdelivr提升国内的访问速度，也可以实现较短的url访问路径。

以下是方法②种`worker`的简单代码示例：
```
const fileTypes = ['需要过滤的cdn文件拓展名','json'];
const cdnDomain = "cdn.jsdelivr.net"
const jsdelivrPath = '/gh/MalitsPlus/ShizuruNotes@master'

addEventListener(
  "fetch",event => {
     let url=new URL(event.request.url);
     let pathNew = "/"
     if(url.hostname!= cdnDomain && fileTypes.includes(url.pathname.split('.').pop())){
        pathNew = jsdelivrPath + url.pathname;
     }
     url.hostname = cdnDomain
     console.log(url.pathname)
     let request=new Request("https://"+cdnDomain+pathNew,event.request);
     event. respondWith(
       fetch(request)
     )
  }
)
```

**Comment by MalitsPlus** [comment]
> ①第一个办法也是最常用的办法，可以使用Cache-Control请求头控制(max-age=0或no-cache)。

jsdelivr 的 cache control 机制作为用户好像控制不了？我看了下 [update_log.json](https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes@master/update_log.json) 的 `max-age` 是 604800。

> ②第二种办法，可以使用cf的worker+CNAME反代https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes/（反代CNAME解析目标是cdn.jsdelivr.net），然后使用cf的Cache Rules控制不cache，既可以利用jsdelivr提升国内的访问速度，也可以实现较短的url访问路径。

虽然 cf 这边可以设置 `max-age=0`，但由于 CNAME 指向的 jsdelivr，所以实际上 jsdelivr 到 cf 这段的 cache control 机制仍然是不变的。

> github变成了我的cdn

你说的我有点心动了，好像这确实是个存放 assets 的好方法，以后有机会试试。

**Comment by PHINEXLISY** [comment]
第一种方法不需要考虑CNAME相关的影响。
`no-cache`确实会生效，设置此值你可以不关心响应头中的缓存属性，但凡是请求头设置了`no-cache`，各类浏览器设备是不会缓存的，如果需要验证此操作，你可以手动开启浏览器的开发者工具，勾选`停用缓存`并查看请求头和响应头以及资源的缓存情况。

然后其实jsdelivr好像是用If-None-Match跟ETAG控制的缓存校验，具体参考https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Conditional_requests
应该是替客户端做好了缓存变动的校验

**Comment by MalitsPlus** [comment]
就算 cf 到客户端的缓存机制可以控制，jsdelivr 到真实原始文件的缓存机制是没法控制的。除非人工向 jsdelivr 发送 purge cache 请求。

测试获取：

> https://raw.githubusercontent.com/MalitsPlus/ShizuruNotes/test/update_log.json

可以看到最新版前面有个 `"test":"3",`

- 直接获取：https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes@test/update_log.json
![image](https://github.com/MalitsPlus/ShizuruNotes/assets/50281195/891870b9-3936-4232-9a3b-223ae0c6e56f)
获得的是修改前没有 `"test"` key 的版本

- 通过 cf worker 获取：https://sn-update.vbb.im
![image](https://github.com/MalitsPlus/ShizuruNotes/assets/50281195/878f88f7-f306-4ae8-9639-4fb93d0f1f98)
获得的是过期的 `"test: 1"` 的版本

worker 在请求 jsdelivr 时和返回给客户端时都有控制 `no-cache`：
https://github.com/MalitsPlus/worker-sn-update/blob/2fd362b958e8e877451084c6493c5a6b9d1a3656/src/index.ts#L42-L58

非要使用 jsdelivr 只能每次请求时加上 commit hash

> https://cdn.jsdelivr.net/gh/MalitsPlus/ShizuruNotes@c197a91/update_log.json

确保请求 path 是独特的。但这样需要动态获取更新接口的地址。

**Comment by PHINEXLISY** [comment]
对吼，忘了jsdelivr短时间内缓存的资源不变的情况了，我一直在想浏览器这边的缓存问题。
我这边是用分支版本控制的所以没有遇到这个问题，
更新频率小于24h的同一个文件在jsdelivr那里确实不会感知到变化。不过，难不倒我(｡･∀･)。，还是有很多办法去解决这个问题的。
兄弟，我的错！
