### ISSUE TITLE
【功能建议】允许用户手动导入unhashed的数据库

### ISSUE THREAD

**Issue by MirrorCubeSquare** [MalitsPlus/ShizuruNotes#95]
如题
提案理由是因为近一段时间以来静流笔记因为hash原因反复无法使用
如果说像是#89一样顾虑沟通成本的话
是否可以考虑手动的措施，允许用户手动导入db
虽然会极大增加使用成本，但是对于愿意搞懂的用户来说依然不难
同时这边的维护精力也能大大降低

或者。。。。
直接官宣archive？

**Comment by MalitsPlus** [comment]
可以，我加一个手动导入 DB 的功能之后就 archive 吧。
